# ansible/playbook.yml

---
- name: Launch EC2 instance in AWS
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    ansible_python_interpreter: /path/to/your/venv/bin/python
    aws_region: "ap-northeast-2"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    instance_type: "t2.micro"
    ami_id: "ami-0ce107ae7af2e92b5"  # Amazon Linux 2 AMI ID
    key_name: "toy-han"
    security_group: "test-toy"
    vpc_id: "vpc-03fdfc3b9a54cfbce"  # Replace with your VPC ID
    subnet_id: "subnet-0221323178722f612"
  tasks:
    - name: Create a security group
      amazon.aws.ec2_group:
        name: "{{ security_group }}"
        description: "My security group"
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        image_id: "{{ ami_id }}"
        aws_region: "{{ aws_region }}"
        vpc_subnet_id: "{{ subnet_id }}"
        wait: yes
        instance_tags:
          Name: "ExampleInstance"
        network:
          assign_pubic_ip: true

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_dns_name }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

    - name: Display public DNS
      debug:
        msg: "EC2 instance public DNS: {{ item.public_dns_name }}"
      with_items: "{{ ec2.instances }}"