# ansible/playbook.yml

---
- name: Launch EC2 instance in AWS
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    aws_region: "ap-northeast-2"
    aws_access_key: "{{ lookup('env', AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    instance_type: "t2.micro"
    ami_id: "ami-0c55b159cbfafe1f0"  # Amazon Linux 2 AMI ID
    key_name: "toy-han"
    security_group: "test-toy"
  tasks:
    - name: Create a security group
      ec2_group:
        name: "{{ security_group }}"
        description: "My security group"
        region: "{{ aws_region }}"
        aws_access_key: "{{ AKIATCKAT5PVKCD7QH3J }}"
        aws_secret_key: "{{ aws_secret_key }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: Launch EC2 instance
      ec2:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        region: "{{ aws_region }}"
        group: "{{ security_group }}"
        wait: yes
        instance_tags:
          Name: "ExampleInstance"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_dns_name }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

    - name: Display public DNS
      debug:
        msg: "EC2 instance public DNS: {{ item.public_dns_name }}"
      with_items: "{{ ec2.instances }}"