# .github/workflows/deploy.yml

name: Deploy to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-pip python3-pip boto boto3 ansible botocore

    - name: Install Ansible collections
      run: |
        echo -e "---\ncollections:\n  - name: amazon.aws\n    version: '>=1.4.0'" > requirements.yml
        ansible-galaxy collection install -r requirements.yml
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: Run Ansible playbook
      env:
        key: ${{ secrets.AWS_SSH_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        ansible-playbook -i ansible/hosts ansible/playbook.yml
