# .github/workflows/deploy.yml

name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3 ansible botocore

    - name: Install Ansible collections
      run: |
        echo -e "---\ncollections:\n  - name: amazon.aws\n    version: '>=1.4.0'" > requirements.yml
        ansible-galaxy collection install -r requirements.yml

    - name: Run Ansible playbook
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        ansible-playbook -i ansible/hosts ansible/playbook.yml
