name: Deploy to aws

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      AWS_REGION: 'ap-northeast-2'

    steps:
    - name: checkout release
      uses: actions/checkout@v3
        
    - name: Upload binary to S3 bucket
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --exclude '*' --include 'index.html'
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
    - name: Deploy rdS
      uses: bitovi/github-actions-deploy-rds@v0.1.5
      with: 
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_default_region: 'ap-northeast-2'

        aws_additional_tags: '{\"some\":\"extra\",\"tag\":\"added\"}'

        tf_state_bucket_destroy: true

        aws_rds_db_enable: true
        aws_rds_db_proxy: true
        aws_rds_db_name: some-db-name
        aws_rds_db_user: myrdsuser
        aws_rds_db_engine: mysql
        aws_rds_db_ingress_allow_all: true
        aws_rds_db_subnets: subnet-05ba0fc17ae5eada5,subnet-05fffc2e1b0b814f1
        aws_rds_db_allocated_storage: 10
        aws_rds_db_max_allocated_storage: 20
        aws_rds_db_instance_class: db.t3.micro
        aws_vpc_id: vpc-086bc9e0e20adff30

        aws_resource_identifier: replaced-this-from
        tf_state_bucket: bitovi-resources
        tf_state_file_name_append: rds-dev-db


