name: Deploy to aws

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      S3_BUCKET_NAME: 'toytest-bucket'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      AWS_REGION: 'ap-northeast-2'

    steps:
    - name: checkout release
      uses: actions/checkout@v3
        
    - name: Upload binary to S3 bucket
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --exclue '*' --include 'index.html'
      env:
        AWS_S3_BUCKET: ${{ S3_BUCKET_NAME }}

