name: Deploy to aws

on:
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  S3_BUCKET_NAME: toytest-bucket

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: checkout release
      uses: actions/checkout@v3
        
    - name: Package install
      run: yarn
        
    - name: Build
      run: yarn build
       
    - name: zip distributions
      run: zip -r practice-deploy.zip  ./

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./practice-deploy.zip s3://$S3_BUCKET_NAME/public

    - name: Deploy with aws codeDeploy
      run: aws deploy create-deployment
        --application-name practice-deploy
        --deployment-config-name CodeDeployDefault.OneAtTime
        --deployment-group-name practice-deploy-group
        --s3-location bucket=$S3_BUCKET_NAME,key=public/practice-deploy.zip,bundleType=zip
